apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: mlops-fraud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: efs-sc
